%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Version 1.1 - 15/9/2020
% D. Lesaint
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


include "tt_dimensions.mzn";
include "tt_ranges.mzn";
include "tt_structures.mzn";
%include "tt_assertions.mzn"; % à revoir
include "tt_predicates.mzn";
include "tt_variables.mzn";
include "tt_constraints.mzn";
include "tt_solve.mzn";
include "tt_output.mzn";
